### ISSUE TITLE
Configure CI/CD: Bitrise

### ISSUE THREAD

**Issue by suho** [nimblehq/ios-templates#101]
Create Bitrise standard configuration file (.yml) for ios templates, must includes some workflows:
- Unit Tests, UI Tests
- Deployment
- Create Pull Requests
- Upload dSYMs files

**Comment by blyscuit** [comment]
Linked to https://www.notion.so/nimblehq/Bitrise-template-for-iOS-project-3deef2ab3a594b1d8bb168fe6cccc647 and #142

**Comment by suho** [comment]
Linked with this issue #142
