### ISSUE TITLE
As an iOS developer, I can see 3 targets after create project from iOS project templates

### ISSUE THREAD

**Issue by suho** [nimblehq/ios-templates#109]
A target specifies a product to build, such as an iOS, watchOS, or macOS app.

When you create a project from a template, targets are added automatically.

If you choose Unit and UI tests when creating a project, the project includes targets for the main app and the test apps.

The recommended targets that we should have in a project:

ProjectName
ProjectNameUnitTests
ProjectNameUITests

**Comment by blyscuit** [comment]
Will need to check if we can put both targets UnitTests and UITests in one folder according to Project Folder Structure. The worst case is to separate `UnitTests` and `UITests` to separate folders instead of one `Tests` folder.

**Comment by suho** [comment]
In this case, we can keep both UnitTests and UITests folders as the default, will create a ticket to research how to put UnitTests and UITests into Tests folder.
