### ISSUE TITLE
SceneDelegate.swift is not initialized correctly after creating a new project with SwitfUI

### ISSUE THREAD

**Issue by nmint8m** [nimblehq/ios-templates#119]
## Bug report

SceneDelegate.swift is not initialized correctly after creating a new project with SwitfUI

Root cause:

![Screen Shot 2020-10-22 at 10 22 57](https://user-images.githubusercontent.com/23162627/96820837-fb3dc280-1450-11eb-851d-fe84e1d678cf.png)

Actual result:

- The class name and function name are not defined in the correct way.

![Screen Shot 2020-10-22 at 10 21 34](https://user-images.githubusercontent.com/23162627/96820849-01cc3a00-1451-11eb-9b57-fd676a340878.png)

Expected result:

SceneDelegate.swift is initialized correctly

**Comment by blyscuit** [comment]
I thought we are not adding `SceneDelegate` by default?

**Comment by suho** [comment]
@blyscuit Yes, currently, we are not support for `SceneDelegate` by default as it's using SwiftUI :D.

**Comment by nmint8m** [comment]
> I thought we are not adding `SceneDelegate` by default?

When choosing `SwiftUI` instead of `Programatically` for `Interface`.

![Screen Shot 2020-10-22 at 11 09 02](https://user-images.githubusercontent.com/23162627/96823618-0dbafa80-1457-11eb-8fdd-39e6cbfe2609.png)
