### ISSUE TITLE
Propose a CI pipeline for Github Action / The tool we want to use

### ISSUE THREAD

**Issue by blyscuit** [nimblehq/ios-templates#134]
## Why 

Web and Android chapter is moving to Github Action but for iOS, Github Action is still too expensive with current pipeline.

## Task

- [ ] Discuss a better alternative to the current pipeline that will save runtime but can cover UnitTest, UITest, and Distribution.
- [ ] Compare to alternatives such as Bitrise.

**Comment by blyscuit** [comment]
Current Project Github Action:
- Run UnitTest and UITest when prompted by typing `run command` to PR comment.
  - UnitTest result is posted back to PR via a bot.
- Run Staging Distribution (only) when merged to `develop` branch.
Current Bitrise:
- Run UnitTest and UITest when pushed and cancel older runs.
- Run UnitTest, UITest, and Staging Distribution when merged to `develop` branch.

**Comment by suho** [comment]
Please check this documentation for more detail: https://www.notion.so/nimblehq/Github-Actions-d009345c7ffb40768fb81d316a46984f
