### ISSUE TITLE
Discuss inclusion of iOS-Fastlane for easier maintenance 

### ISSUE THREAD

**Issue by blyscuit** [nimblehq/ios-templates#135]
## Why

https://github.com/nimblehq/ios-fastlane is currently an important part of iOS projects, yet it is not periodically maintained.

## Request

- [ ] Discuss including `ios-fastlane` within this repo for easy maintenance or other alternative.
- [ ] Include a script to install `ios-fastlane` to new projects.
- [ ] Agree upon and update `ios-fastlane` project with up-to-date code.
- [ ]  Include `ios-fastlane` as a Compass article.

**Comment by blyscuit** [comment]
One other alternative is to maintain the code in the same repo but have it as a submodule in this repo.

**Comment by suho** [comment]
We are going to use this repository as a git template, so I think we can put the whole Fastlane folder into this repository, then the code can be maintainable.

**Comment by blyscuit** [comment]
Will be done in https://github.com/nimblehq/ios-templates/issues/140
