### ISSUE TITLE
Include UITest Template files

### ISSUE THREAD

**Issue by blyscuit** [nimblehq/ios-templates#140]
## Why

We need to have UITests template files into the iOS templates, so people can use it easily instead of copying from projects to projects.

## Acceptance Criteria

- Add template files into the UITests folder

**Comment by suho** [comment]
@blyscuit I just updated the description for this issue, feel free to update and add more content into this issue

**Comment by blyscuit** [comment]
Awaiting more code review.

**Comment by suho** [comment]
@blyscuit I suggest bringing the pull request again into the `ios-chapter` channel. People will jump into your PR again :D
