### ISSUE TITLE
Add Bitrise Template

### ISSUE THREAD

**Issue by blyscuit** [nimblehq/ios-templates#142]
## Why

Our project need support Bitrise for CI/CD

## Acceptance Criteria

Add `bitrise.yml` to perform a pipeline:

- Static code linter,
- Match,
- Unit tests,
- UI tests,
- Deploy to Firebase Distribution

Another pipeline for:
- Static code linter,
- Match,
- Unit tests,
- UI tests,
- Deploy to iTunes Connect

The configuration file must take values from Secret such as Apple ID, App ID, etc.

Feel free to use https://github.com/nimblehq/ios-fastlane

**Comment by suho** [comment]
@phongvhd93 Please check this issue again, I just added information about documentation on Notion, please add the documentation on Notion.

**Comment by suho** [comment]
I will close this issue as @phongvhd93 has finished the template file. For document, please check this issue #182
