### ISSUE TITLE
Add Project Configurations Document

### ISSUE THREAD

**Issue by suho** [nimblehq/ios-templates#147]
## Why

As we are moving to `@3.0.0`. We also need to restructure our document. Need to add the Project Configurations Document in Notion

## Acceptance Criteria

- Add the Project Configurations Document into Notion: https://www.notion.so/nimblehq/iOS-Templates-ac74dffa740744be9ac2d5c3905856dc
- Update back to the wiki page after getting approvals

**Comment by nmint8m** [comment]
I mark this ticket with 3 points. As I will reuse the content on Wiki and add more descriptive content.
