### ISSUE TITLE
Add Project Dependencies Document

### ISSUE THREAD

**Issue by suho** [nimblehq/ios-templates#148]
## Why

As we are moving to `@3.0.0`. We also need to restructure our document. Need to add the Project Dependencies Document in Notion

## Acceptance Criteria

- Add the Project Configurations Document into Notion: https://www.notion.so/nimblehq/iOS-Templates-ac74dffa740744be9ac2d5c3905856dc
- Update back to the wiki page after getting approvals

**Comment by nmint8m** [comment]
I mark this ticket with 5 points. 

For this ticket, I will reuse the content on Wiki and add more descriptive content. Besides, I think I will rearrange the content to make it clearer.
