### ISSUE TITLE
Missing pre-setup Wiki for Github Action template

### ISSUE THREAD

**Issue by markgravity** [nimblehq/ios-templates#168]
## Bug report

After trying to use our new Github Action template in [nimble medium](https://github.com/nimblehq/nimble-medium-ios) project, I found out that we're missed the pre-setup wiki as I list down below:

- Setup Firebase 
  + Create a project for staging & production
  + Configure Firebase Crashlytics
- Setup Fastlane Match
  + Create a private repo to store certs & provisioning profiles
  + Setup authentication for Fastlane match to access into this repo
  + Initialize certs & provisioning profiles

### Can we use one private repo for all projects?
Words from Fastlane match docs
```
Git Storage

Use one git branch per team. match also supports storing certificates of multiple teams in one repo, by using separate git branches. If you work in multiple teams, make sure to set the git_branch parameter to a unique value per team. From there, match will automatically create and use the specified branch for you.
```
### Do we should create `ios-dev@nimblehq.co` AppStoreConnect account and use it for our Fastlane Match? 

Refer [this](https://codesigning.guide)

## What's Next?
Create pre-setup WIKI for Github Action template

**Comment by suho** [comment]
@markgravity For the pre-setup wiki, Firebase and Fastlane already have their documentation (setup project, setup private repo or create certs and profiles). So I think we can use their document link and put it into the `iOS Dependencies` page.

**Comment by suho** [comment]
@markgravity 
1. For the question `Can we use one private repo for all projects?`
- For client projects: We must not use shared private repo for all client projects.
- For Nimble internal projects (medium-ios, ...): Yes, we can use a shared private repo for all our internal projects.
	- The shared private repo contains 1 distribution cert, 1 development cert. And provisioning profiles for all projects (based on bundle id)

2. For the question `Should we create ios-dev@nimblehq.co?`
We should not create a shared account with the admin role. Team Lead should care about create/revoke certs and create/delete provisioning profiles with an admin account. Other developers just need to get all certs and profile from the match repo and install it.

**Comment by markgravity** [comment]
> @markgravity For the pre-setup wiki, Firebase and Fastlane already have their documentation (setup project, setup private repo or create certs and profiles). So I think we can use their document link and put it into the `iOS Dependencies` page.

Agree, atleast we should give they some links about what they need to do before they can use our Github Action 👍 
Btw, in Firebase setup we need a script to dynamic copy `GoogleService-Info.plist` base on configuration
```

**Comment by suho** [comment]
@markgravity Please check all documents from the [Notion page](https://www.notion.so/nimblehq/iOS-Templates-ac74dffa740744be9ac2d5c3905856dc). And add comments on it so the author can add more references links for you.
