### ISSUE TITLE
Fix: R.generated.swift need to be created to include into project

### ISSUE THREAD

**Issue by markgravity** [nimblehq/ios-templates#208]
## Issue

`R.generated.swift` need to be created to include into the project after being generated by tuist
<img width="487" alt="Screen Shot 2021-10-13 at 16 36 31" src="https://user-images.githubusercontent.com/17875522/137107955-43f60262-8520-4b63-bdf1-c59cce723fff.png">
 
## Expected

`R.generated.swift` should be added in Main Target
 
## Steps to reproduce

1. Run `sh make.sh`
2. Build the app by Xcode
3. Don't see `R.generated.swift` in `Rswift` folder

**Comment by blyscuit** [comment]
The reference to the folder seems to be missing after generated with Tuist. The file is created by the R.Swift command successfully.

**Comment by suho** [comment]
@markgravity Please help me to fix this bug, thank you
