### ISSUE TITLE
Clear all warnings on fresh generated project

### ISSUE THREAD

**Issue by markgravity** [nimblehq/ios-templates#209]
## Why

With a fresh generated project, it shouldn't contain any warnings
 
Currently
<img width="434" alt="Screen Shot 2021-10-13 at 16 38 27" src="https://user-images.githubusercontent.com/17875522/137108319-5541a971-f21f-4139-b5ef-6d87fd885adb.png">

## Acceptance Criteria
- [ ] No warnings from Xcode after build in fresh generated project

**Comment by suho** [comment]
@markgravity Please help me to implement this chore ticket
