### ISSUE TITLE
Pull Request review Workflow seems to be failing

### ISSUE THREAD

**Issue by blyscuit** [nimblehq/ios-templates#220]
## Issue

Pull Request review Workflow seems to be failing because `error: Build input file cannot be found: '/CustomDynamicFontTests/Sources/Mocks/Sourcery/AutoMockable.generated.swift'`
 
<img width="727" alt="Screen Shot 2021-11-05 at 12 48 03" src="https://user-images.githubusercontent.com/6356137/140464884-dd4aaf38-d8b4-4f5e-af2d-03da53f40ff7.png">

## Expected

When push, test should successfully build.
 
## Steps to reproduce

1. Use the template
2. run `sh make.sh`
3. Push to a Github Repo.
4. Trigger the test workflow.

## Note
This seems to be because the order of the lane `build_and_test`. I modified `TestManager.rb` to
```
# TestManager.rb
# frozen_string_literal: true

class TestManager
  def initialize(fastlane:, device:, output_directory:)
    @fastlane = fastlane
    @device = device
    @output_directory = output_directory
  end

  def test(scheme:, targets:)
    @fastlane.scan(
      scheme: scheme,
      device: @device,
      output_directory: @output_directory,
      code_coverage: true,
      result_bundle: true,
      only_testing: targets,
      fail_build: false
    )
  end
end
```
and 
```
# fastfile

  desc 'Build and Test'
  lane :build_and_test do
    test_manager.test(
      scheme: Constants.TESTS_SCHEME, 
      targets: [Constants.TESTS_TARGET, Constants.UI_TESTS_TARGET]
    )
  end
```

To make it work.

**Comment by blyscuit** [comment]
@suho @llleyelll any reason we should distinct `build` and `test` in `TestManager`?

**Comment by suho** [comment]
@blyscuit I think we don't need `build_for_testing` anymore, in the past, some projects need to run tests with different targets. Btw, the root cause of this issue is related to the `build_and_test` lane and its order?

**Comment by blyscuit** [comment]
The issue is with when we use `test_without_building: true`, the file `autogenerated` is not created then it would fail. If you run the command locally, it works fine as long and `autogenerated` is already exited.

**Comment by suho** [comment]
@blyscuit Currently, we need to run all tests targets at the same time to export the test result bundle for the xcov, so I prefer to update the TestManager
