### ISSUE TITLE
Improve Code Coverage Report in Dangerfile

### ISSUE THREAD

**Issue by suho** [nimblehq/ios-templates#225]
## Why

Currently, in a pull request, we are showing the code coverage of all files in the project, we need to update Dangerfile to show only code coverage of file changes.

## Acceptance Criteria

- Filter file changes in pull request
- Show code coverage of all file changes instead of all files of the project

**Comment by markgravity** [comment]
Can we put them into `collapsible` as well? Sometimes it's too long and so painful when scrolling through them
![Screen Shot 2021-11-25 at 13 34 07](https://user-images.githubusercontent.com/17875522/143391635-245cb03b-3dda-49e4-a2b7-2186c3e4dd0c.png)
