### ISSUE TITLE
Improve the infrastructure setup for iOS Projects

### ISSUE THREAD

**Issue by suho** [nimblehq/ios-templates#248]
## Why

For iOS projects, the infrastructure setup for deployment and distributions pipelines requires work on a CI platform (Github Actions, Gitlab, or Bitrise), Firebase, and iTunes Connect.

While progress has been made over the years to ensure that initial sprints do not only include chores, infrastructure work still represents a significant time investment for our team and clients.

To improve the infrastructure to start a new project, we should focus on making the iOS templates to be further templated and automated:

- Update [the Constants file](https://github.com/nimblehq/ios-templates/blob/master/fastlane/Constants/Constants.rb) with Placeholder Xcode style
- Add script to ask the developer to update [the Constants file](https://github.com/nimblehq/ios-templates/blob/master/fastlane/Constants/Constants.rb) if they want to update it right after the setup script. If yes, open [the Constants file](https://github.com/nimblehq/ios-templates/blob/master/fastlane/Constants/Constants.rb) by Xcode.
- Add scripts to support Setting up the minimum iOS version.
 
## Who Benefits?

iOS Chapter

## Resources

https://www.notion.so/nimblehq/Improve-the-infrastructure-setup-for-iOS-Projects-ea319f14527a4fabaf81329f6acd2333

**Comment by blyscuit** [comment]
What do you think if instead of including these values in the setup script we:
- Use `CSV` file then a script to replace data in `Constants.rb` file from the `CSV`.
of
- Web (google form like) to generate `Constants.rb` file.

This allow the benefits of 
- Letting user go back and forward while editing the constant file might give a better UX.
- Reduce error from using terminal to fill data.

**Comment by suho** [comment]
That's a good point! The idea of this issue is to improve the infrastructure setup. Instead of manually updating the infrastructure values (Firebase ID, match repo URL, ...), improving the setup with automation is our goal.

CSV, Web form, or even a `.env` file looks good to me 💭. Let's see other ideas :D

**Comment by suho** [comment]
cc @nimblehq/ios-chapter What do you guys think?

**Comment by markgravity** [comment]
I still prefer `.env` so that we can change it later or sharing 🤔

**Comment by blyscuit** [comment]
These are the current values that we need to change when generating a new project.
```
PROJECT_FIREBASE_APP_ID_STAGING
PROJECT_FIREBASE_APP_ID_PROD
PROJECT_TEAM_ID
DEV_PORTAL_APPLE_ID
API_KEY_ID
ISSUER_ID
```
I think 6 (currently) is too much of variables to modify from Terminal.

Another suggestion that makes more sense is using Xcode placeholder text. Then we can ask the user if they want to modify the Constants.rb at the last line of make.sh, if so we can run script to open Xcode `open -a Xcode ..../Constants.rb`

<img width="394" alt="Screen Shot 2022-08-02 at 11 10 05" src="https://user-images.githubusercontent.com/6356137/182289918-2972ba46-6fd1-455a-80a3-c02de5e9f6bd.png">

**Comment by phongvhd93** [comment]
Related to CI/CD, we should let developers choose which service they want to use (Bitrise, GitHubAction), and after choosing the preferred one, the script will remove other ci/cd template file
