### ISSUE TITLE
Fix: Bitrise Templates has wrong indentation

### ISSUE THREAD

**Issue by vnntsu** [nimblehq/ios-templates#260]
## Why

- Currently, we can't use`bitrise.yml` since its workflow named `deploy_staging` is the wrong indentation.
- `test` workflow is using a redundant step with Fastlane `n_xcov`.

![Screen Shot 2022-04-08 at 09 09 13](https://user-images.githubusercontent.com/17830319/162349264-f2ba8f90-fe28-4c93-9de1-c29b219d6269.png)
 
## Who Benefits?

iOS guys who are setting up a project 🥳

**Comment by phongvhd93** [comment]
This was fixed in this [PR](https://github.com/nimblehq/ios-templates/pull/263)
