### ISSUE TITLE
[RFC] Supports SwiftUI + Combine frameworks from the beginning

### ISSUE THREAD

**Issue by suho** [nimblehq/ios-templates#276]
## Issue

Based on [this epic](https://github.com/nimblehq/ios-templates/issues/272), currently, the `ios-templates` repository only supports for UIKit + RxSwift from the beginning. For developers who want to use SwiftUI + Combine frameworks from the beginning, they can't use our templates. They need to fix a lot of things (e.g. remove the AppDelegate file, remove RxSwift out of the project, ...)
 
## Solution

Our template needs to support SwiftUI + Combine frameworks from the beginning.

We can update the `make.sh` scripts to support SwiftUI + Combine or check more about `tuist` with the command [init](https://docs.tuist.io/tutorial/get-started) or [scaffold](https://docs.tuist.io/commands/scaffold/) to init a project from a template. I see they can do like this `tuist init --platform ios --template swiftui`.

## Who Benefits?

iOS Chapter and iOS developers

## What's Next?
 - [ ] Discuss with iOS chapter members and finalize the approach.
 - [ ] Create stories for the SwiftUI + Combine epic.
 - [ ] Implement and create pull requests. 🙌

**Comment by blyscuit** [comment]
@suho I would like to start on this one as I can transfer my knowledge from the recent project. 

Also the template update is not going as smoothly and would like to switch to something with more promising result for now.

**Comment by suho** [comment]
@blyscuit Please go ahead! If you need my help, feel free to raise here

**Comment by suho** [comment]
@blyscuit I added this initiative for you: https://www.notion.so/nimblehq/SwiftUI-and-Combine-for-iOS-Templates-94e33afdcc8f494e9cfddbdabd42d171?pvs=4

**Comment by blyscuit** [comment]
@suho Can I close this? https://www.notion.so/nimblehq/SwiftUI-and-Combine-for-iOS-Templates-94e33afdcc8f494e9cfddbdabd42d171 initiative is done.

**Comment by suho** [comment]
@blyscuit Yes, we can close it :+1:
