### ISSUE TITLE
Fastlane - Modify code signing before creating build

### ISSUE THREAD

**Issue by vnntsu** [nimblehq/ios-templates#311]
## Why

- In terms of creating a build based on environment, `Build Settings` supports only one certificate and profile at a time. So in the case, we want to have multiple builds with different signing, we need to modify them automatically by Fastlane.
- For more information, please checkout fastlane's [update_code_signing_settings](https://docs.fastlane.tools/actions/update_code_signing_settings/) 
 
## Who Benefits?

@nimblehq/ios-chapter

**Comment by blyscuit** [comment]
Is the idea is to have multiple `app_identifier` and we can use `MatchManager.rb` to sign according to which CI script is running?

**Comment by vnntsu** [comment]
@blyscuit yes, it is.
A few more cases that we can consider:
- Build ad-hoc and AppStore for `Release Production`. Since in project code signing, we can set only `ad-hoc` or `AppStore` at a time.
- Also `Team Id` and `Team Name`.

**Comment by blyscuit** [comment]
@vnntsu This looks like it is done in https://github.com/nimblehq/ios-templates/pull/450. Will close after confirmation from you 🙏

**Comment by vnntsu** [comment]
@blyscuit yes, you can close it now 🙏
