### ISSUE TITLE
Add steps in CI/CD templates to support upload builds and dSYM files to build artifacts of CI/CD platforms (Github Actions, Bitrise)

### ISSUE THREAD

**Issue by suho** [nimblehq/ios-templates#351]
## Why

Technically, after a release build on a CI/CD platform, we can not download the build file and dSYM files. We need to support uploading builds and dSYM files to build artifacts. So might need those files later.
 
## Who Benefits?

Everyone (Developers, Product Managers, Clients)

**Comment by blyscuit** [comment]
I'll work on the Github Actions version of this first.

**Comment by blyscuit** [comment]
Will be done again in https://github.com/nimblehq/ios-templates/issues/383, @suho @vnntsu this one can be closed.
