### ISSUE TITLE
As a developer, I can use Fastlane Swift on GitHub Actions templates

### ISSUE THREAD

**Issue by suho** [nimblehq/ios-templates#377]
## Why

After migrating from Fastlane Ruby to Fastlane Swift, we need to use it on GitHub Actions templates.
 
## Who Benefits?

iOS Developers.

**Comment by ducbm051291** [comment]
@suho Consider this is already done since we merged the migrate-develop branch to develop branch. We can close this issue. What do you think?

**Comment by vnntsu** [comment]
@ducbm051291 You're right, I'll close it. Thanks!
