### ISSUE TITLE
As a developer, I can see the App Icon after generating the project

### ISSUE THREAD

**Issue by suho** [nimblehq/ios-templates#380]
## Why

Currently, we can not upload a build to TestFlight after generating the project because of App Icon. I think it is better to have an App Icon after generating the project.

## Acceptance Criteria

- Setup the app icon while generating a new project
- Use our logo for the app icon: https://assets.nimblehq.co/logo/dark/logo-dark-icon-1024.png

## Design

Nimble Logo: https://assets.nimblehq.co/logo/dark/logo-dark-icon-1024.png

**Comment by blyscuit** [comment]
Currently, the TestFlight test workflow is using this image https://github.com/nimblehq/ios-templates/blob/main/fastlane/Tests/appicon.png we can remove this image and use dark icon one provided by Su in the TestFlight test, to reduce the number of files in the template and not confuse the users.
