### ISSUE TITLE
[RFC] Update a specific name for deploying staging build to firebase workflow

### ISSUE THREAD

**Issue by nkhanh44** [nimblehq/ios-templates#423]
## Issue

When working with GitHub Action, sometimes I am confused with `deploy_Firebase.yml` and `deploy_Release_Firebase.yml`. Especially, back to work on iOS-template for a long time, we have to run our eyes over 8 yml files looking for staging workflow and rethink "this is `deploy_Release_Firebase.yml`, so where is staging firebase?" or `deploy_Firebase.yml` is for staging or not.

## Solution
- Change the name from `deploy_Firebase.yml` to `deploy_staging_firebase.yml`.
- Change the name's description from `Deploy Build To Firebase` to `Deploy Staging Build To Firebase`.

## Who Benefits?
Template users.

**Comment by blyscuit** [comment]
Agree, also change `deploy_release_firebase` to `deploy_production_firebase`.

**Comment by nkhanh44** [comment]
good suggestion @blyscuit, I will add it too 👍 .
