### ISSUE TITLE
[RFC] Update Xcode build formatter from xcpretty to xcbeautify for buildApp and scan actions

### ISSUE THREAD

**Issue by nkhanh44** [nimblehq/ios-templates#430]
## Why
- `xcbeautify` is a little beautifier tool for `xcodebuild`. Similar to `xcpretty`, but faster. Detail at [Features](https://github.com/tuist/xcbeautify#features).
 
| xcpretty      | xcbeautify |
| ----------- | ----------- |
| <img width="300" height="600" src="https://user-images.githubusercontent.com/25881847/216530504-4c292c97-c2df-4b59-b513-880ea186e04a.png" >   | <img width="300" height="600" src="https://user-images.githubusercontent.com/25881847/216530405-972819a5-42e0-4f70-814f-0e338dec3964.png" >  |

## Who Benefits?

Template users.

**Comment by nkhanh44** [comment]
Hi @vnntsu,
When implementing `buildApp` and `scan` actions of Fastlane swift, we used `xcpretty` for `xcodebuildFormatter` and marked it as "_Default `xcbeautify` will never work_". Is there any specific reason, or it just failed when we run these actions above?
I'm trying to work on this in order to bring `xcpretty` back :D, your experience will help a lot 🙏 . Thank you.

**Comment by vnntsu** [comment]
@nkhanh44 It seemed we've not installed `xcbeautify` yet and I'm quite convinced by its features now, especially `2x faster than xcpretty`. So I agree to include it in 💪
