### ISSUE TITLE
Fix: Lint and add SwiftFormat ignore to Fastlane Swift

### ISSUE THREAD

**Issue by blyscuit** [nimblehq/ios-templates#433]
## Issue

SwiftFormat is being run on the folder `fastlane` automatically.

There are also some files in `fastlane/` needed lint fixes.

## Expected

Running the app from the template should not show lint/format warnings. 
 
## Steps to reproduce

1. Run `make.sh`.
2. Run app.
3. Observe lint warnings.
<img width="518" alt="Screen Shot 2023-01-20 at 12 36 02" src="https://user-images.githubusercontent.com/6356137/213641851-986cee5d-fdbd-43e9-bb49-aaf920afad32.png">
<img width="524" alt="Screen Shot 2023-01-20 at 12 36 32" src="https://user-images.githubusercontent.com/6356137/213641870-a1d934dc-0748-425b-9f32-c14a3d141c26.png">
<img width="521" alt="Screen Shot 2023-01-20 at 12 38 45" src="https://user-images.githubusercontent.com/6356137/213641873-71862030-1ac2-4cd9-b86e-0950654cf5fd.png">
<img width="518" alt="Screen Shot 2023-01-20 at 12 38 38" src="https://user-images.githubusercontent.com/6356137/213641879-445aa8ef-f34f-4fe6-8469-58de135e2d5b.png">

**Comment by ducbm051291** [comment]
> There are also some files in fastlane/ needed lint fixes.

@blyscuit Can you list for me which files needed lint?

**Comment by blyscuit** [comment]
@ducbm051291 You can run `swiftlint` and `swiftformat` to see if any other files need change. Some of the files I found are in the screenshots 🙏.

**Comment by ducbm051291** [comment]
@blyscuit I intend to exclude only the folder fastlane/swift :D
