### ISSUE TITLE
Fix: Dangerfile could not find `/fastlane/Constants/Constants`

### ISSUE THREAD

**Issue by blyscuit** [nimblehq/ios-templates#443]
## Issue

Danger could not find the file `require './fastlane/Constants/Constants' ` and would crash on CICD. './fastlane/Constants/Constants' was removed and change to './fastlane/Constants/Constants.swift'

Make sure Danger has all its variables available when using `make.sh` without './fastlane/Constants/Constants'.

## Expected

Danger can run on CICD with success.
 
## Steps to reproduce

1. Use the template on a new repo.
2. Run `make.sh`.
3. Make sure the project can run test locally.
4. Create PR on the new repo.
5. Danger should run and comments its output.

**Comment by suho** [comment]
@blyscuit this issue is duplicated with #399? 🤔

**Comment by blyscuit** [comment]
Duped and fixed with #399
