### ISSUE TITLE
[Bug] Fix: deliverable_setup.sh not working

### ISSUE THREAD

**Issue by edgarss** [nimblehq/ios-templates#453]
## Issue

We dont have DeliverableConstants.rb in the project in the project anymore
 
## Expected

Have the script assist in setting up constants for github or bitrise ci/cd
 
## Steps to reproduce

1. run `sh deliverable_setup.sh`
2. get result: `The file /{path}/fastlane/Constants/DeliverableConstants.rb does not exist.`

**Comment by suho** [comment]
@edgarss What version of the iOS-templates are you using?

Just checked the [deliverable_setup.sh](https://github.com/nimblehq/ios-templates/blob/main/deliverable_setup.sh), it now opens the `Constants.swift`

**Comment by edgarss** [comment]
Youre right @suho , i was looking in a cloned project that is a bit behind.
