### ISSUE TITLE
Update Node.js Version in Workflows to Avoid Deprecated Actions

### ISSUE THREAD

**Issue by nkhanh44** [nimblehq/ios-templates#463]
## Why

Currently, the version of Node.js being used in our workflows is 12, which has deprecated certain actions. To ensure that our workflows continue to function properly, we need to update the following actions to use Node.js version 16:

- `actions/checkout@v2` -> `actions/checkout@v3`
- `webfactory/ssh-agent@v0.5.4` -> `webfactory/ssh-agent@v0.7.0`
- `actions/cache@v2` -> `actions/cache@v3`

Updating these actions will ensure that our workflows are using the latest version of Node.js and will help us avoid any potential issues or errors.

The announcement from Github: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

_Warning in Action:_

![Screenshot 2023-03-31 at 15 41 46](https://user-images.githubusercontent.com/25881847/229077210-54139c50-8160-4316-876f-0c2ec925844c.png)

## Who Benefits?

@nimblehq/ios-chapter

**Comment by nkhanh44** [comment]
@vnntsu  Do you think of any updates or changes that should be considered in conjunction with the switch to Node.js 16 too? I can add here, too 🙇

**Comment by vnntsu** [comment]
@nkhanh44 I'm not entirely sure I can keep up with all the changes this time. 

If you have any more changes to propose, please let me know, and I can review them later. 
Please feel free to continue making progress, and if we find anything lacking, we can always improve it at a later time.

**Comment by nkhanh44** [comment]
Thank you for the reply, I will continue with the current update 🙏
