### ISSUE TITLE
Add Test upload build to Firebase workflows

### ISSUE THREAD

**Issue by ducbm051291** [nimblehq/ios-templates#471]
## Why

We only validate newly added features/chores/bugs via test upload build to TestFlight. We should update deploying to Firebase workflow and create a test upload build to Firebase to validate them. Because unexpected or weird behaviors may occur, and features/chores may not work in the staging environment while deploying to Firebase.

## Acceptance Criteria

- Create Test upload staging build to Firebase
 
## Who Benefits?

Developers

**Comment by suho** [comment]
@ducbm051291 You should raise and discuss with the chapter before implementing. @vnntsu Should be the one who planned for the milestone ;).

**Comment by ducbm051291** [comment]
> @ducbm051291 You should raise and discuss with the chapter before implementing. @vnntsu Should be the one who planned for the milestone ;).

Ok understood. I have discussed this with @vnntsu before creating this

**Comment by vnntsu** [comment]
@ducbm051291 @suho This seems reasonable regarding the need to validate a build with Firebase uploading. However, it's already uploaded the `Production` build to AppStore, this should be only `Staging` for Firebase.

As discussed with @ducbm051291, I believe we're lacking `Staging` build to validate something like #465. It requires that the new feature should be worked on both `Staging` and `Production`.

cc: @nimblehq/ios-chapter
