### ISSUE TITLE
Update workflows build runs-on: macos-latest

### ISSUE THREAD

**Issue by ducbm051291** [nimblehq/ios-templates#474]
## Why

- Currently, our workflows build `runs-on: macos-12`, the same as `macos-latest`. We should update to macos-latest to have the latest stable mac os version. 

- Ref: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

![CleanShot 2023-04-13 at 14 20 08](https://user-images.githubusercontent.com/24598204/231684728-de6a91d9-5e95-44c7-9192-419cdab18fc8.png)
 
## Who Benefits?

Developers.

**Comment by blyscuit** [comment]
@ducbm051291 Could you check if all Actions are on `macOS-lastest`. I remember we had that PR 🤔 .

**Comment by ducbm051291** [comment]
@blyscuit I think we should update this to `self-hosted` instead 😁

**Comment by ducbm051291** [comment]
Due to setting up the self-hosted runner for the iOS chapter. This issue is unnecessary.
