### ISSUE TITLE
[Feature] Add option: github-self-hosted while generating the project

### ISSUE THREAD

**Issue by ducbm051291** [nimblehq/ios-templates#498]
## Why

The update to the workflow for the iOS template repository must incorporate the newly set up **GitHub self-hosted runner** on a **Mac Mini** from **MacStadium**. The document can be found [HERE](https://www.notion.so/nimblehq/Provision-Custom-MacOS-Runner-for-GitHub-Actions-ace7181d7bf24896804c7e3313c9c956?pvs=4).

The update will add a new option - `github-self-hosted` - in generating project commands in make.sh file
 
## Who Benefits?

- Development Team: Faster build times and improved performance lead to increased productivity and reduced waiting times.
- Project Managers and Stakeholders: Increased reliability and stability facilitate smoother project management and timely delivery.
- Clients and End Users: The updated workflow delivers more robust and bug-free applications, improving the user experience.
- Company: Utilizing the self-hosted runner lowers costs and maximizes credits, reducing dependency on GitHub-hosted runners and providing scalability and flexibility for resource allocation.

**Comment by suho** [comment]
@ducbm051291 For iOS templates, currently, when generating the project, we need to choose: `github`, `bitrise`, `codemagic`. I would prefer to add one more option (e.g. `github-self-hosted`), so the team can easily switch between different platforms.

cc @blyscuit

**Comment by blyscuit** [comment]
@suho Good idea. This issue can be for creating the new workflow files and the setup script 👍

**Comment by ducbm051291** [comment]
Ok, got it
