### ISSUE TITLE
Fix: Unit/UI test build error

### ISSUE THREAD

**Issue by markgravity** [nimblehq/ios-templates#518]
## Issue

Running Unit/UI test failed due to a build error on test specs

![CleanShot 2023-07-24 at 15 21 49@2x](https://github.com/nimblehq/ios-templates/assets/17875522/309b8a8c-647b-4109-b31d-881807c59506)

 
## Expected

Build successfully
 
## Steps to reproduce

1. Run `make.sh`
2. Run Unit/UI test on Xcode
3. Receive errors from Xcode
![CleanShot 2023-07-24 at 15 21 49@2x](https://github.com/nimblehq/ios-templates/assets/17875522/309b8a8c-647b-4109-b31d-881807c59506)

**Comment by blyscuit** [comment]
@markgravity I am wondering if this is related to tuist folder naming bug and is fixed in #514 🤔

**Comment by markgravity** [comment]
Fixed
