### ISSUE TITLE
Remove xcbeautify

### ISSUE THREAD

**Issue by nkhanh44** [nimblehq/ios-templates#562]
## Why

All Tuist xcbeautify repository's releases  are removed due to unknown reason. It's breaking the CI flow, so we need to remove it rn.

![Screenshot 2024-08-01 at 14 54 13](https://github.com/user-attachments/assets/4bd2ae31-af04-40b0-91c4-db0514cbbcd7)

 
## Who Benefits?

Users

**Comment by markgravity** [comment]
We shouldn't remove it cause it will produce a very long output in the CI/CD pipeline.

![CleanShot 2024-08-05 at 11 16 46](https://github.com/user-attachments/assets/4033f827-de89-49d4-978c-8eae8105ffed)
