### ISSUE TITLE
Standard file organization

### ISSUE THREAD

**Issue by suho** [nimblehq/ios-templates#95]
The goal is to standardize our file organization.

Currently, we have some different folder structure on our projects, so we need to make file structure "official", so we can use for all next projects.

From version 1.0.0 and some projects that I'm working on, the file structure will be like this:

```swift
ROOT
├─ Sources
   ├─ Design // should we keep this? or separate a Views folder into `{Project Name}` folder @@
   ├─ {Project Name}
      ├─ Application
        ├─ AppDelegate
        ├─ Constants
        ├─ Entitlements
        ├─ Localizations
        ├─ Resources
      ├─ Extensions
      ├─ Models
      ├─ Modules
      ├─ Protocols
      ├─ Services
         ├─. Network
      ├─ Utilities
         ├─ Logger // For example
├─ Tests
   ├─ UnitTests // could perhaps create subdirectory for Modules, Services...
   ├─ UITests // create subdirectory for Screens
```

- Sources/Design: This folder contains all custom views, custom layout (for collection view), fonts, action sheet controller... Mostly, everything related to `Design ~ View`

The structure above ☝️ is just my suggestion, please give your point and discuss more about this, then we can define a good structure for next projects

**Comment by NutanNiraula** [comment]
For unit tests I think it would make sense to follow something similar to project folder structure. We don't need all the folders of course but we can use `Extensions`, `Modules`, `Models`, `Services` and `Utilities` maybe 🤔

**Comment by suho** [comment]
@NutanNiraula Yes, that's my idea, based on the project structure, we will create the same folder into Unit tests. For example, if we write unit tests for Login module, we will create a submodule `Modules/Login` into unit tests

**Comment by suho** [comment]
Updated structure based on discussion:

```swift
ROOT
├─ Design // stuffs related to views that's shared among projects, move it to NimbleExtension?
├─ Sources
   ├─ Application
     ├─ AppDelegate
     ├─ Constants
     ├─ Entitlements
     ├─ Localizations
     ├─ Resources
   ├─ Extensions
   ├─ Models
   ├─ Modules
   ├─ Protocols
   ├─ Services
      ├─ Network
   ├─ Utilities
      ├─ Logger // For example
   ├─ Views // custom or common views that belongs to the project
├─ Tests
   ├─ UnitTests // could perhaps create subdirectory for Modules, Services...
   ├─ UITests // create subdirectory for Screens
```

**Comment by nmint8m** [comment]
[Slack](https://nimble-co.slack.com/archives/G418DBL2W/p1599727390012000)

**Comment by nmint8m** [comment]
[Wiki](https://github.com/nimblehq/ios-templates/wiki/Standard-file-organization)
