### ISSUE TITLE
Build configurations

### ISSUE THREAD

**Issue by suho** [nimblehq/ios-templates#96]
We need to think about Build Configurations on the iOS Template project, technically, there is many build configurations that are using on our projects: Debug, Staging, Release, UAT...

We need to discuss about this to bring the **basic build configurations** into the template project. 

This is my suggestion, we will need these basic configurations after create a new project

- **Debug** for development: **DEBUG** flag defined
- **Staging** for releasing beta: **STAGING** flag defined
- **Release** for releasing to App Store: **RELEASE** flag defined

**Comment by NutanNiraula** [comment]
@nimblehq/ios-chapter 
I have thought of few things related to the configurations. I want to bring up things I am not sure for all apps and things I think would make sense. This is not exhaustive list but somethings I think might make sense for us to discuss. Please check.

1. If we should add SIT or UAT configurations or both. I think UAT should be enough for most projects but I could be wrong.
2. If we should use external xcconfig files to define configuration externally.
3. If we should add AppTransport Security (ATS) arbitrary load enabled in debug and then removed for production using build phase script.
4. If we should add Settings Bundle in every project or not
5. If we should show Xcode warning / error when expression takes longer time to evaluate or function takes too long to compile. This might help us to improve build time later.
6. If we should / should not generate dSYM file for debug builds
7. If we want to select certain constants like baseURL from configuration or we add it using Environment enum or use settings bundle or use launch arguments.

I am in favor of 
1. Renaming Release configuration to be called Production 
2. Renaming Debug to Dev
3. Have Debug and Release configuration for Dev, (SIT, UAT) (if we have one or both) and Production like in The1

**Comment by nmint8m** [comment]
[Slack](https://nimble-co.slack.com/archives/G418DBL2W/p1600157706014400)
