### ISSUE TITLE
Basic Schemes for template

### ISSUE THREAD

**Issue by suho** [nimblehq/ios-templates#97]
Need discussion to have the final schemes on iOS template.

- **{{Project Name}} Debug**: Staging environment with development provisioning profile
- **{{Project Name}} Staging**: Staging environment with Ad-hoc distribution provisioning profile
- **{{Project Name}} test suite**: Configured for both Unit Tests and UI Tests
- **{{Project Name}} unit tests**: Configured for Unit Tests
- **{{Project Name}} ui tests**: Configured for UI Tests
- **{{Project Name}}**: Production level for releasing to App Store

**Comment by nmint8m** [comment]
Reference: https://github.com/nimblehq/ios-templates/wiki/Project-configurations

The recommended schemes that we should have in a project:

- {{ProjectName}}
- {{ProjectName}}Staging
- {{ProjectName}}SIT (optional)
- {{ProjectName}}UAT
